<?php 
include_once('Migration/ContactsMigration.php');
include_once('Migration/EmploymentMigration.php');
include_once('Migration/BSMigration.php');
include_once('Migration/MSMigration.php');
include_once('Migration/PhdMigration.php');
include_once('Migration/FellowMigration.php');
include_once('Migration/AssocMigration.php');
include_once('Migration/GradMigration.php');
include_once('Migration/TrainingMigration.php');
include_once('Migration/EngagementResearchMigration.php');

/*migrateContacts();
migrateEmployments();
migrateBS();
migrateMS();
migratePhd();
migrateFellow();
migrateAssocResearch();
migrateGradResearch();
migrateTrainings();*/
migrateEngagementResearch();